Create chromosome alias in CoordSystem object
Ensembl/ensembl pull request #527
Opened 2020-10-16 10:57 UTC by nwillhoft

## Description

As described in [JIRA ticket ENSCORESW-3021](https://www.ebi.ac.uk/panda/jira/browse/ENSCORESW-3021), sequence assembly data has changed in format in recent years, resulting in recent databases having only a single 'primary_assembly' coordinate system. This is compared to older assembly data with multiple coordinate systems including: 'chromosome', 'contig', 'scaffold'.

## Use case

Currently, a coordinate system named 'chromosome' may not exist in an Ensembl database, due to a change in sequence assembly formatting in databases created in the last few years. Examples include the Parus major and Clupea harengus databases, which contain a single coordinate system named 'primary_assembly'. If a user requests a chromosome slice object and there is no explicitly-named chromosome coordinate system in the query database, this new feature uses karyotype-based attributes in the database to identify a coordinate system to add an appropriate ('chromosome') alias to.

## Benefits

Where an Ensembl Core species database does not have coordinate system named chromosome, this code will create an alias to the appropriate coordinate system when a user requests a chromosome slice object, as long as the requested name has associated karyotype attributes.

## Possible Drawbacks

Once the tests have been updated (as mentioned below), there are no drawbacks that I can think of.

## Testing

Yes, tests have been added to `coordSystem.t`.

_If so, do the tests pass/fail?_

The tests in `coordSystem.t` pass.

_Have you run the entire test suite and no regression was detected?_

**The test suite as a whole fails and I have left this PR as a draft in order to deal with this issue.**

- One example is that `assemblyException.t` is now seemingly failing because of these alias chromosome changes. The number of chromosome features returned by these tests has increased as a result of these changes, and no longer matches the expected count. 

```
modules/t/assemblyException.t .................................... 2/?
#   Failed test 'Returned 94 features'
#   at modules/t/assemblyException.t line 38.
#          got: '243'
#     expected: '94'

#   Failed test 'Fetched 24 features'
#   at modules/t/assemblyException.t line 51.
#          got: '173'
#     expected: '24'
modules/t/assemblyException.t .................................... 4/?
#   Failed test 'Fetched 24 features'
#   at modules/t/assemblyException.t line 77.
#          got: '173'
#     expected: '24'
# Looks like you failed 3 tests of 8.
```

2020-10-16 11:18 UTC, nwillhoft commented
The test suite is passing when run by travis-ci. As various tests failed when I ran the test suite locally, I need to check how my local environment differs to that used by travis-ci.

2020-10-19 08:39 UTC, magaliruffier commented
Two areas to investigate regarding the tests:
- patches and other alternative regions have chromosome as a coordinate system but are flagged as alternative with an entry in the assembly exception table
It might be worth checking whether the alias fetching SQL needs to be updated to deal with these
- some tests can run fine on their own, but fail when the whole test suite is run.
When the whole test suite is run, test databases are re-used between tests rather than created from scratch
If any of the tests adds/updates data, this can affect downstream tests

2020-10-23 09:46 UTC, nwillhoft commented
> Two areas to investigate regarding the tests:
> 
> * patches and other alternative regions have chromosome as a coordinate system but are flagged as alternative with an entry in the assembly exception table
>   It might be worth checking whether the alias fetching SQL needs to be updated to deal with these
> * some tests can run fine on their own, but fail when the whole test suite is run.
>   When the whole test suite is run, test databases are re-used between tests rather than created from scratch
>   If any of the tests adds/updates data, this can affect downstream tests

Thanks mag. I believe the failed tests I saw locally were due to your second point of test dbs being re-used because if I only run the tests in `assemblyException.t`, they all pass as expected.

2020-10-23 15:47 UTC, ens-bwalts requested changes

2020-10-23 15:47 UTC, ens-bwalts commented on modules/Bio/EnsEMBL/CoordSystem.pm
> +  my ( $name, $version, $top_level, $sequence_level, $default, $rank, $alias_to ) =
Add the -ALIAS_TO option to the documentation

2020-10-23 16:13 UTC, mira13 commented
Please check and if needed add appropriate changes to coordinate system apadtor that creates, removes and updates coordinatesystem object, to also support alias_to

2020-10-23 16:15 UTC, mira13 requested changes
Please update CoordinateSystemAdaptor store/update/remove methods if needed to support new field.

2020-10-26 14:22 UTC, nwillhoft commented
> Please update CoordinateSystemAdaptor store/update/remove methods if needed to support new field.

Thanks @mira13 . I've discussed this with @ens-bwalts and alias-related changes to the database are currently planned for a future date. For this current feature we've been working on updating the CoordSystem and SliceAdaptor objects, and will include your suggestions in a plan to update database schema changes etc. at a future date.

2020-10-26 16:39 UTC, mira13 commented
@nwillhoft it can happen that current changes will be merged in current release, and future planned - not. It is a bug in release.

2020-10-27 10:07 UTC, nwillhoft commented
Have discussed database schema updates with @magaliruffier and @ens-bwalts. They have decided that the database schema will need updating at a future date and have approved the scope of the current changes (i.e. code changes to modify CoordSystem objects). @mira13 's point needs keeping in mind - that users might file bug reports if they find a new alias field in the code and expect to find it in the database (but it's not there).

2020-10-27 10:07 UTC, nwillhoft commented
Will add in more checks to ensure users can only create an alias called 'chromosome'.

2020-10-27 13:12 UTC, mira13 approved these changes

2020-10-29 10:15 UTC, ens-bwalts approved these changes
Changes as requested

2020-10-29 11:31 UTC, merged