Create calls in fetch_by_region to _fetch_by_seq_region_synonym
Ensembl/ensembl pull request #536
Opened 2020-11-03 14:39 UTC by nwillhoft

## Description

Add in calls from `fetch_by_region` to `_fetch_by_seq_region_synonym`. Remove the code from `fetch_by_region` that has been refactored into `_fetch_by_seq_region_synonym`.

## Use case

Any `fetch_by_region` examples that use a synonym or synonym-wildcard as the sequence region name input argument.

## Benefits

Will make SliceAdaptor::fetch_by_region easier to read.

## Possible Drawbacks

None I can think of.

## Testing

_Have you added/modified unit tests to test the changes?_

_If so, do the tests pass/fail?_

_Have you run the entire test suite and no regression was detected?_

2020-11-04 12:03 UTC, magaliruffier requested changes
Github diff is not very easy on these changes but it looks OK overall
A few prints that can probably be removed

2020-11-04 12:03 UTC, magaliruffier commented on modules/Bio/EnsEMBL/DBSQL/SliceAdaptor.pm
> +use Data::Dumper;
remove

2020-11-04 12:03 UTC, magaliruffier commented on modules/Bio/EnsEMBL/DBSQL/SliceAdaptor.pm
> +        print "Running synonym-match method...\n";
remove

2020-11-04 12:03 UTC, magaliruffier commented on modules/Bio/EnsEMBL/DBSQL/SliceAdaptor.pm
> +        print "Running synonym-match method...\n";
remove

2020-11-04 12:03 UTC, magaliruffier commented on modules/Bio/EnsEMBL/DBSQL/SliceAdaptor.pm
> +        print "Slice data has been returned...\n";
remove

2020-11-04 12:03 UTC, magaliruffier commented on modules/Bio/EnsEMBL/DBSQL/SliceAdaptor.pm
> +          print "Using matched name $matched_name derived from query name $seq_region_name...\n";
remove

2020-11-05 09:54 UTC, nwillhoft commented on modules/Bio/EnsEMBL/DBSQL/SliceAdaptor.pm
> +use Data::Dumper;
Removed.

2020-11-05 09:54 UTC, nwillhoft commented on modules/Bio/EnsEMBL/DBSQL/SliceAdaptor.pm
> +        print "Running synonym-match method...\n";
Removed.

2020-11-05 09:54 UTC, nwillhoft commented on modules/Bio/EnsEMBL/DBSQL/SliceAdaptor.pm
> +        print "Slice data has been returned...\n";
Removed.

2020-11-05 09:54 UTC, nwillhoft commented on modules/Bio/EnsEMBL/DBSQL/SliceAdaptor.pm
> +          print "Using matched name $matched_name derived from query name $seq_region_name...\n";
Removed.

2020-11-05 09:57 UTC, nwillhoft commented
Will share this draft PR with other teams (Production, Web, Regulation) that have contacted me to say that they use fetch_by_region. I want to make sure that this refactoring work doesn't cause any breaking changes.

2020-11-09 16:47 UTC, nwillhoft commented
Tester (@james-monkeyshines) has found a bug that I need to fix:

"When run against the chimp database, the datacheck raises an error. It is checking for regions named 'PT', which is commonly used for plastids, and chimp just happens to have a region with a synonym ('PTBY-13L8') that "fuzzy-matches". I'm in the process of fixing the datacheck to not use fuzzy matching, because that is not desirable in this case; as the datacheck currently stands, your new branch fails with an uncaught error:
Can't call method "dbID" on an undefined value at /homes/jallen/work/repositories/ensembl/modules/Bio/EnsEMBL/DBSQL/SliceAdaptor.pm line 896"

Code he ran to get error:
```
# (branch release/103 of ensembl-datacheck):
cd ensembl-datacheck
perl scripts/run_datachecks.pl -host mysql-ens-mirror-1 -port 4240 -user ensro -dbname pan_troglodytes_core_102_3 -name PlastidsAnnotated
```

2020-11-17 11:09 UTC, nwillhoft commented
Rebased on master to integrate latest updates.

2021-01-22 13:31 UTC, nwillhoft commented
Rebased on master earlier today to integrate latest changes.

2021-02-03 12:06 UTC, nwillhoft commented
Rebased on master to integrate latest changes.

2021-02-05 13:14 UTC, nwillhoft commented
Web pages created in test sandbox web server look fine.

2021-02-09 11:17 UTC, magaliruffier approved these changes
Changes were reviewed previously and look good, tests have been comprehensive

2021-02-15 18:34 UTC, ens-bwalts approved these changes
This looks like a good refactor - `$coord_system_name` never really gets used after fetching the coord_system, and disregarding it actually simplifies some things for the case where a synonym can refer to multiple seq_regions.

2021-02-16 09:28 UTC, merged