Fix external_db.txt
Ensembl/ensembl pull request #558
Opened 2021-01-27 11:53 UTC by mira13

## Description

Some test dbs has wrong newlines. Fix for it

## Use case

travis build, unit tests

## Benefits

Correct unit testing

## Possible Drawbacks

not found

## Testing

no

_If so, do the tests pass/fail?_

_Have you run the entire test suite and no regression was detected?_

yes

2021-01-28 09:27 UTC, nwillhoft commented on modules/t/test-genome-DBs/parus_major1/core/external_db.txt
> -50850	CGSNL	\N	KNOWNXREF	0	Committee on Gene Symbolization, Nomenclature and Linkage of the Rice Genetics Cooperative	MISC	\N	\N	The Committee on Gene Symbolization, Nomenclature and Linkage (CGSNL)
The proposed change applied to this DOI breaks the link. Please can the DOI link be kept as it currently is, i.e. "https://doi.org/10.1007/s12284-008-9004-9"

2021-01-28 09:34 UTC, nwillhoft requested changes
Have made an in-line comment about a DOI link needing to stay as it currently is (because a '/' replaced with a space is breaking the link). All other changes look good. Build checks are passing.

2021-01-28 12:00 UTC, nwillhoft approved these changes
The removal of extra new line and white space characters looks good.

2021-02-03 11:22 UTC, TamaraNaboulsi approved these changes
All wrong newlines removed from files, looks good.

2021-02-03 11:32 UTC, merged