[ENSCORESW-3683] Software/Schema Release Version Update to 106
Ensembl/ensembl pull request #572
Opened 2021-06-14 14:56 UTC by nwillhoft

## Requirements

- Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion;
- Review the [contributing guidelines](https://github.com/Ensembl/ensembl/blob/master/CONTRIBUTING.md#why-could-my-pull-request-be-rejected) for this repository; remember in particular:
    - do not modify code without testing for regression
    - provide simple unit tests to test the changes
    - if you change the schema you must patch the test databases as well, see [Updating the schema](https://github.com/Ensembl/ensembl/blob/master/CONTRIBUTING.md#updating-the-schema)
    - the PR must not fail unit testing

## Description

As part of Core Release Activity 1, update the software and schema release versions from 105 to 106.

## Use case

After the REST code branching, the software and schema release versions on the master branch of this repo require updating for the subsequent release (i.e. 106).

## Benefits

N/A

## Possible Drawbacks

N/A

## Testing

_Have you added/modified unit tests to test the changes?_

_If so, do the tests pass/fail?_

_Have you run the entire test suite and no regression was detected?_

2021-06-16 15:16 UTC, magaliruffier commented
Changes include increment in ApiVersion as well as SQL patch file
All test databases have been updated with new release version, as per SOP

SQLlite build fails with issues getting the Compara checkout, unrelated to this PR
MySQL build fails because it is trying to compare releases 104 and 105, as 106 is now yet available on a main branch
This should get resolved once the PR is merged into master

2021-06-16 15:16 UTC, magaliruffier approved these changes

2021-06-18 09:27 UTC, TamaraNaboulsi requested changes
The file sql/table.sql also needs to be updated with the new version and patch file (lines 311 and 317).

2021-07-13 07:55 UTC, TamaraNaboulsi approved these changes
Version bumped to 106 and new patch file added. All looks good.

2021-07-19 08:55 UTC, merged